# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- task: IISWebAppDeploymentOnMachineGroup@0
  inputs:
    WebSiteName: 'https://webapppipeline.azurewebsites.net/'
    Package: '$(System.DefaultWorkingDirectory)\**\*.zip'
pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

  
